version: 2

before:
  hooks:
    - go mod download
    - go mod tidy
builds:
  - binary: gobackup
    ldflags:
      - "-extldflags=-static -s -w -X main.version={{.Version}}"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
release:
  prerelease: auto